version: '2'
services:
    etd:
        build: .
        ports:
         - "8084:8084"
        networks:
         - new
    semanticserver:
        image: jermnelson/semantic-server-core:dev
        ports:
         - "8080:8080"
         - "9999:9999"
        networks:
         - new
    web:
        build: 
            context: .
            dockerfile: DockerfileNginx
        ports:
         - "80:80"
         - "443:443"
        networks:
         - new

networks:
  new:   
